'use client';
import Image from 'next/image';
import { useSelector } from 'react-redux';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { FaArrowLeft } from 'react-icons/fa';
import Link from 'next/link';
import Head from 'next/head';

interface Item {
  id?: number;
  title?: string;
  category?: string;
  author?: string;
  img?: string;
  price?: number;
  sales?: number;
  feedback?: number;
  feedback_count?: number;
}

const Product = () => {
  const [open, setOpen] = useState<boolean>(false);
  const [product, setProduct] = useState<Item>({
    id: undefined,
    title: '',
    category: '',
    author: '',
    img: '',
    price: 0,
    sales: 0,
    feedback: 0,
    feedback_count: 0,
  });

  const router = useRouter();
  const id = Number(router.query.id);

  const data: Item[] = useSelector(
    (state: any) => state.products.product_list || []
  );

  useEffect(() => {
    const item: any = data.find((element) => element.id === id);
    setProduct(item);
  }, [id, product]);

  useEffect(() => {
    const handleKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setOpen(false);
      }
    };
    document.addEventListener('keydown', handleKey, true);
  }, [open]);

  if (!product) {
    return null;
  }

  return (
    <div className=" w-full flex max-[768px]:flex-col max-[768px]:justify-center items-center  pt-24 pl-12 max-[768px]:pl-0 bg-gray-300 dark:bg-slate-950 pt-5 justify-between bg-cover min-h-screen">
      <Head>
        <title>{product.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div
        onClick={() => setOpen(false)}
        className={` ${
          open ? 'visible scale-1 opacity-90' : 'invisible scale-0 opacity-0'
        } fixed transition-all ease-in-out duration-500 flex w-full min-h-screen bg-cover bg-black top-0 left-0 right-0 bottom-0 z-50 text-center items-center justify-center `}
      >
        <Image
          src={`/Products/${product.img}.jpg`}
          width="500"
          height="500"
          className={`opacity-100 transition-all ease-in-out duration-1000`}
        />
      </div>
      <div
        onClick={() => setOpen(true)}
        className="w-1/2 text-center max-[1000px]:text-left max-[768px]:w-full max-[768px]:text-center"
      >
        <img
          src={`/Products/${product.img}.jpg`}
          width="600"
          height="600"
          className="rounded-xl transition-all duration-300 hover:scale-125 max-[768px]:w-3/4 max-[768px]:my-0 max-[768px]:mx-auto "
        />
      </div>
      <div className="w-1/2 flex flex-col pt-8 max-[1000px]:pl-4 font-bold max-[768px]:w-full max-[768px]:pl-0 max-[768px]:items-center">
        <p className="text-3xl font-bold">{product.title}</p>
        <p className="mt-4 text-xl">{product.author}</p>
        <div className="w-full mt-5 flex max-[768px]:justify-center">
          <button className="w-50 bg-yellow-400  px-8 py-4 max-[1000px]:px-4 max-[1000px]:py-0.5 max-[768px]:py-4 max-[768px]:px-8 inline-block  text-center rounded-xl hover:bg-yellow-500 font-bold text-xl mr-5">
            Buy now
          </button>
          <button className="w-1/4 bg-yellow-400  px-8 py-4 max-[1000px]:px-4 max-[1000px]:py-0.5 text-center rounded-xl hover:bg-yellow-500  max-[1000px]:text-[16px] font-bold text-xl">
            Add to cart
          </button>
        </div>
        <p className="mt-2">You can pay by using:</p>
        <div className="flex w-full max-[768px]:justify-center">
          <Image width="100" height="100" src="/payments/mastercard.png" />
          <Image width="100" height="100" src="/payments/visa.png" />
        </div>
      </div>
    </div>
  );
};

export default Product;
