import Layout from '../../layout';
import ProductBoard from './ProductBoard';
import Header from './Header';
import { useState } from 'react';
import { useSelector } from 'react-redux';
import Head from 'next/head';

const ProductPage: React.FC = () => {
  const [openCart, setOpenCart] = useState<boolean>(false);

  const statusBar = useSelector((state: any) => state.bar.setBar);
  return (
    <Layout>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div
        className={`flex transition-all duration-500 ease-in-out ${
          statusBar ? 'w-4/5' : 'w-full'
        }  p-5 max-[400px]:ml-16  flex-col items-center relative`}
      >
        <Header open={openCart} setOpenCart={setOpenCart} />
        <ProductBoard open={openCart} setOpenCart={setOpenCart} />
      </div>
    </Layout>
  );
};

export default ProductPage;
